package com.medical.backend.entity;

public enum SpecialtyType {
    CARDIOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    GYNECOLOGY,
    OPHTHALMOLOGY,
    ENT,
    UROLOGY,
    GASTROENTEROLOGY,
    ENDOCRINOLOGY,
    PULMONOLOGY,
    PSYCHIATRY,
    ONCOLOGY,
    RADIOLOGY,
    ANESTHESIOLOGY,
    GENERAL_SURGERY,
    PLASTIC_SURGERY,
    EMERGENCY_MEDICINE,
    FAMILY_MEDICINE
}